
    var enLang={
        OTHER:          "Other",
        CONTINUE:       "Continue",
        CANCEL:         "Cancel",
        BEFORE:         "Before",
        AFTER:          "After",
        READ:           "Read",
        UNREAD:         "Unread",
        NOW:            "Now",
        TODAY:          "Today",
        YESTERDAY:      "Yesterday",
        NOTIFICATIONS:  "Notifications",
        AT:             "at",

        PHA_NAM:    "Pharmacy Name",
        ALL_NOT:    "All Notifications",
        empty_invoice_confirm_msg: "Empty Invoice means remove all items and reset invoice like new order. Do you wanna continue",
        done_request_confirm_msg: "You can't edit or canceled this invoice after submit it to adminstration. Are you sure that you have done",
    },
    arLang = {
        OTHER: "أخرى",
        CONTINUE:       "استمرار",
        CANCEL:         "إلغاء الأمر",
        BEFORE:         "قبل",
        AFTER:          "بعد",
        READ:           "مقروء",
        UNREAD:         "غير مقروء",
        NOW:            "الآن",
        TODAY:          "اليوم",
        YESTERDAY:      "الأمس",
        NOTIFICATIONS:  "الإشعارات",
        AT:             "عند",

        PHA_NAM:    "اسم الصيدلية",
        ALL_NOT:    "كل الإشعارات",
        empty_invoice_confirm_msg : "إفراغ الفاتورة يعني حذف كل الأصناف من هذه الفاتورة وإعادتها كفاتورة جديدة. هل تريد الإستمرار",
        done_request_confirm_msg: "لا يمكن تعديل أو إلغاء الفاتورة بعد إرسالها إلى الإدارة. هل أنت متأكد أنك أتممتها",
    };